<center><h1>Numpy Full Notes</h1></center>
<center>github : jibrankhalil-jk</center>



importing numpy

In [1]:
import numpy as np

<h2 style="color:yellow; font-weight:bold;">.array()</h2>

`np.array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0, like=None)`

`object` can be any iterable  

Such as
- ```list```
- ```tuple```
- ```set```
- ```range``` (iterator)

All iterables can be used to create a numpy array, such as ```dict```

`dtype` is used to set the data type of the array

`copy` If True then the array data is copied. If None, a copy will only be made if __array__ returns a copy, if obj is a nested sequence, or if a copy is needed to satisfy any of the other requirements (dtype, order, etc.). Note that any copy of the data is shallow, i.e., for arrays with object dtype, the new array will point to the same objects. See Examples for ndarray.copy. For False it raises a ValueError if a copy cannot be avoided. Default: True.

`order` (default : K ) Specify the memory layout of the array.
    

<img src="assets/images/order_table.png" style="width:40%;">

`subokbool` If True, then sub-classes will be passed-through, otherwise the returned array will be forced to be a base-class array (default).

`ndminint` Specifies the minimum number of dimensions that the resulting array should have. Ones will be prepended to the shape as needed to meet this requirement.

In [2]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
arr = np.array([1,2,3,4,5,6,7,8,9,10],ndmin=2)
arr

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [8]:
arr = np.array([1,2,3,4,5,6,7,8,9,10],dtype='float')
arr

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

<h2 style="color:yellow; font-weight:bold;">.empty_like()</h2>

`empty_like`
Return an empty array with shape and type of input.

```np.empty_like(prototype, dtype=None, order='K', subok=True, shape=None, *, device=None)```

In [42]:
b = [[1,2],[3,4]]
arr = np.empty_like(b)
arr

array([[0, 0],
       [0, 0]])

<h2 style="color:yellow; font-weight:bold;">.ones_like()</h2>

`ones_like`
Return an array of ones with shape and type of input.

```numpy.ones_like(a, dtype=None, order='K', subok=True, shape=None, *, device=None)```

In [51]:
b = [[1,2],[3,4]]
arr = np.ones_like(b)
arr

array([[1, 1],
       [1, 1]])

<h2 style="color:yellow; font-weight:bold;">.full_like()</h2>

`full_like`
Return a new array with shape of input filled with value.

```numpy.full_like(a, fill_value, dtype=None, order='K', subok=True, shape=None, *, device=None)```

In [ ]:
b = [[1,2],[3,4]]
arr = np.full_like(b , 2)
arr

<h2 style="color:yellow; font-weight:bold;">.zeros_like()</h2>

`zeros_like`
Return an array of zeros with shape and type of input.



In [52]:
b = [[1,2],[3,4]]
arr = np.zeros_like(b)
arr

array([[0, 0],
       [0, 0]])

<h2 style="color:yellow; font-weight:bold;">.empty()</h2>

`empty`
Return a new uninitialized array.

```numpy.empty(shape, dtype=float, order='C', *, device=None, like=None)```

In [61]:
b = [[1,2],[3,4]]
arr = np.empty(2)
arr

array([9.9e-324, 1.5e-323])

<h2 style="color:yellow; font-weight:bold;">.ones()</h2>


`ones`
Return a new array setting values to one.

```numpy.ones(shape, dtype=None, order='C', *, device=None, like=None)```


<h2 style="color:yellow; font-weight:bold;">.zeros()</h2>



`zeros`
Return a new array setting values to zero.

```numpy.zeros(shape, dtype=float, order='C', *, like=None)```


<h2 style="color:yellow; font-weight:bold;">.full()</h2>


`full`
Return a new array of given shape filled with value.

```numpy.full(shape, fill_value, dtype=None, order='C', *, device=None, like=None)[source]```


<h2 style="color:yellow; font-weight:bold;">.copy()</h2>


`copy`
Return an array copy of the given object.

```numpy.copy(a, order='K', subok=False)```